### ISSUE TITLE
Add a new tf feature extractor

### ISSUE THREAD

**Issue by dougsouza** [toshas/torch-fidelity#23]
Hello,

I have tf inception model finetuned specific for my dataset. I would like to use this model to compute IS and FID using torch fidelity. How do I convert this inception model to torch and preserve behavior as you did?

Can you share how you did it?

Thanks,

Douglas

**Comment by toshas** [comment]
If it is the same model, use this script: https://github.com/toshas/torch-fidelity/blob/master/utils/util_convert_inception_weights.py

If the model is different, you will also need to create a compatible `torch.nn.Module`
