### ISSUE TITLE
Running the code 

### ISSUE THREAD

**Issue by mountains-high** [toshas/torch-fidelity#31]
Hi, 
Thank you for your work
While running ```fidelity --gpu 0 --isc --input1 ~/images/```
I got following error:
```
ValueError: Input descriptor "input" field can be either an instance of Dataset, GenerativeModelBase class, or a string, such as a path to a name of a registered dataset (cifar10-train, cifar10-val, stl10-train, stl10-test, stl10-unlabeled), a directory with file samples, or a path to an ONNX or PTH (JIT) module

```
Could you help me to solve this issue, please?
Thank you

**Comment by toshas** [comment]
Thanks for the output, although it is not clear from it that `./images/` and `~/images/` is the same directory.
When I try to reproduce a similar setting, here is what I get as a full output:
```
$ fidelity --isc --input1 ~/images/
Creating feature extractor "inception-v3-compat" with features ['logits_unbiased']
Extracting features from input1
Looking for samples non-recursivelty in "/Users/anton/images/" with extensions png,jpg,jpeg
Found 4 samples
Processing samples                                                                                                 
```
Can you please share the full output?

**Comment by mountains-high** [comment]
Hello, 
Thank you for pointing this out. I tried  this ```fidelity --gpu 0 --isc --input1 ./images/```. Thank you very much, it works well.
