### ISSUE TITLE
Score calculation for paired dataset

### ISSUE THREAD

**Issue by lizijue** [toshas/torch-fidelity#34]
Hi,

I also calculate the FID , KID and LPIPS scores between pair images (predictions and GTs), and I am comparing two networks, but the results show the model that has a lower LPIPS value but higher FID and KID scores at the same time.

So I wanna know is this what you say hard to interpret? What may be the reason for this phenomenon? Could it be a lack of diversity since the higher similarity?

I will very appreciate if you could help me.

**Comment by toshas** [comment]
This library is designed for computing metrics and scores on unpaired data, typically an output of generative models. Using it for paired data where you have GT makes little sense. For one reason, having pairs of prediction and ground truth allows one to use metrics like LPIPS or PSNR, which are more reliable than distribution metrics, to evaluate model quality. Second (and re "hard-to-interpret") distribution diversity/similarity metrics are prone to many corner cases and may output scores inconsistent with human perception of model outputs. Third, all these complex distribution metrics rely on dimensionality reduction through feature extractors, such as pretrained VGG backbones, to reduce input image dimensions to a single feature vector of several K elements size. All these steps contribute to the overall lack of reliability compared to reliable pairwise metrics and have to be used only when GT is unavailable. HTH, closing as not an issue.

**Comment by lizijue** [comment]
Thank you for answering my questions, and it helps me a lot!
