### ISSUE TITLE
Question about PRC merge to master

### ISSUE THREAD

**Issue by GiannisPikoulis** [toshas/torch-fidelity#38]
Hello. 

Thanks for the awesome repo. When is the PRC branch going to be merged to main? Is it going to happen anytime soon?

**Comment by toshas** [comment]
Hi, thanks for the kind words,
Which PR are you asking about? Currently, there are two, and none of them are called PRC.
At this point, I don't see any PRs submitted in accordance with the contributing code https://github.com/toshas/torch-fidelity/blob/master/CONTRIBUTING.md. For the remaining, I will consider them upon the next round of release preparation.
