### ISSUE TITLE
About the value of FID

### ISSUE THREAD

**Issue by zy-charon** [toshas/torch-fidelity#44]
Hello, I would like to ask why I get a negative value when calculating FID with pictures in the same folder. Is this normal?
![image](https://user-images.githubusercontent.com/74723536/227895649-3056784c-c079-4ed7-bedd-3e8ed49ad68d.png)

**Comment by toshas** [comment]
Theoretically speaking, FID values are positive, but in this case (1) the distributions are the same, meaning we expect zero (2) the covariance will likely be singular or ill-conditioned, which may result in unstable computation. Numerical precision issues may arise in this case, which is normal. 5e-5 is a reasonable precision error with 32-bit floating-point computation, this is 2 to 4 orders of magnitude less than the typically-reported error bars in scientific papers.
