### ISSUE TITLE
ValueError: KID subset size 1000 cannot be smaller than the number of samples (input_1: 876, input_2: 876). Consider using "kid_subset_size" kwarg or "--kid-subset-size" command line key to proceed.

### ISSUE THREAD

**Issue by may-phyu** [toshas/torch-fidelity#45]
Hi I am so happy to get your sharing valuable source code to calculate the metrics I do appreciate it and I am currently facing this bug when I train with my custom generated images. May I know how I should solve it? Please help me where should I need to change. Thank you so much.

**Comment by toshas** [comment]
Hi, thanks for the kind words, 
This is not a bug but a natural constraint: the metric requires certain parameters in line with your data. If you have fewer samples than the default value, feel free to override this value with the `--kid-subset-size 100` command line option (if you want 100, or any other number). Pay attention to the standard deviation of your metric results!

**Comment by may-phyu** [comment]
A million thanks for your kindly help I do appreciate it
