### ISSUE TITLE
A better way to compute the FID

### ISSUE THREAD

**Issue by francois-rozet** [toshas/torch-fidelity#46]
Hello, I think the following implementation of the Fréchet distance is faster than the current one and would allow to drop the `scipy` dependency.

```python
def frechet_distance(mu_x: Tensor, sigma_x: Tensor, mu_y: Tensor, sigma_y: Tensor) -> Tensor:
    a = (mu_x - mu_y).square().sum(dim=-1)
    b = sigma_x.trace() + sigma_y.trace()
    c = torch.linalg.eigvals(sigma_x @ sigma_y).sqrt().real.sum(dim=-1)

    return a + b - 2 * c
```

The implementation is based on two facts:

1. The trace of $A$ equals the sum of its eigenvalues.
2. The eigenvalues of $\sqrt{A}$ are the square-roots of the eigenvalues of $A$.

**Comment by toshas** [comment]
Thanks a lot for the suggestion! Perhaps a step further would be to use `linalg.eigvalsh` as covariances are hermitian. When I replaced the block https://github.com/toshas/torch-fidelity/blob/master/torch_fidelity/metric_fid.py#L46-L63 with `tr_covmean = np.sum(np.sqrt(np.linalg.eigvalsh(sigma1.dot(sigma2))))`, the metric stops working in the simple scenarios: `fidelity -g 0 --fid --input1 cifar10-train --input2 cifar10-val`. When printing the values of eigenvalues, it is immediately clear that some of them are negative: `-1.2  -0.7  -0.6 ...  37.9  90.1 155.5`. The current code works by (1) adding extra conditioning and (2) discarding the imaginary part. It is thus not immediately clear how the new solution should look to simulate the "legacy" FID computation issues. However, I agree that it makes sense to have a correct way after we fully understand the impact of swapping implementations. Let me know what you think about it,

Thanks,
Anton

**Comment by francois-rozet** [comment]
Hello, indeed a covariance matrix is hermitian, but the product of two hermitian matrices is not in the general case.

**Comment by francois-rozet** [comment]
By the way, `torchmetrics` adopted this way of computing the FID: https://github.com/Lightning-AI/torchmetrics/issues/1705.
