### ISSUE TITLE
Doubts about the calculation of FID

### ISSUE THREAD

**Issue by ilem777** [toshas/torch-fidelity#7]
Hello, this project of yours is very helpful for my work. I would like to ask, isn't the calculation of FID calculated ten times and then take the mean and standard deviation? (like calculating KID), can you modify it?

**Comment by toshas** [comment]
It depends on the evaluation protocol; in many papers FID is calculated over the entire dataset once. I agree that it would make sense to unify this aspect with Inception Score calculation. You can fork the repo and modify it in place to your needs. If your change is backwards compatible with the current API, you are welcome to submit a pull request so this change will appear in 0.3.0 release.

**Comment by ilem777** [comment]
Thank you for your understanding, I will try to modify it.
